- apps/elf-council-frontend/src/ui/app/Header.tsx
> Fix sigfigs in deposited amount in app header

- .eslintrc
- .gitignore
- apps/elf-council-frontend/package.json
- apps/elf-council-frontend/tests/e2e/.eslintrc.js
- apps/elf-council-frontend/tests/e2e/config.json
- apps/elf-council-frontend/tests/e2e/specs/overview-page.specs.js
- apps/elf-council-frontend/tests/e2e/tsconfig.json
- package.json
- yarn.lock
Adds the basis of e2e testing via synpress
> Add synpress e2e testing

- yarn.lock
Temp fix. (https://github.com/a16z/zkp-merkle-airdrop-lib/pull/3)
> Lock snarkjs version

- apps/elf-council-frontend/src/ui/gsc/GSCHistory.tsx
- apps/elf-council-frontend/src/ui/gsc/GSCPortfolioCard.tsx
- apps/elf-council-frontend/src/ui/gsc/useGSCStatus.ts
GSC has a timelock for new GSC members after joining of 4 days on mainnet. We were not handling this state in the portfolio card.
> GSC Idle State

- apps/elf-council-frontend/src/ui/gsc/GSCButtons.tsx
- apps/elf-council-frontend/src/ui/gsc/GSCHistory.tsx
- apps/elf-council-frontend/src/ui/gsc/GSCOverviewSection.tsx
- apps/elf-council-frontend/src/ui/gsc/useCandidates.tsx
- Copy for GSC page
- invalidate cache after joining GSC
- useCandidates hook fetches knownDelegate info
- idle gsc history tooltip
> GSC UI Copy

- apps/elf-council-frontend/src/elf-snapshot/endpoints.ts
- apps/elf-council-frontend/src/ui/app/Sidebar.tsx
- apps/elf-council-frontend/src/ui/gsc/GSCOverviewSection.tsx
- apps/elf-council-frontend/src/ui/gsc/ThresholdProgressBar.tsx
- apps/elf-council-frontend/src/ui/overview/PortfolioCard.tsx
- apps/elf-council-frontend/src/ui/proposals/GSCProposalsSection.tsx
- apps/nft-interface/.env
- packages/council-proposals/src/snapshot.ts
- Added some hyperlinks to gsc copy. 
- Removed gsc feature flag.
- Added gsc snapshot links to proposals repo and fe
> Remove GSC UI feature flag

- apps/elf-council-frontend/src/ui/zkclaim/zkp-merkle-airdrop-lib/src/index.ts
- yarn.lock
- update yarn.lock with correct snark version
- remove unused file
> fix snarkjs version

- apps/elf-council-frontend/src/ui/gsc/GSCMemberProfileRow.tsx
- apps/elf-council-frontend/src/ui/gsc/GSCOverviewSection.tsx
- apps/elf-council-frontend/src/ui/gsc/useCandidates.tsx
- apps/elf-council-frontend/src/ui/gsc/useVotingPowerByDelegates.ts
- Refactor vote power counting algo to correctly count votes from the vesting vault. This also fixes mis-sorting of voting power in rising delegates view.
- Added a nullish check to kick button conditional rendering. Ideally we are exposed the isLoading state, this can be done in a follow up.
> GSC UI - Fix rising delegates and flashing kick button on init

- apps/council-testnet/.eslintrc
- apps/council-testnet/package.json
Heads up, I've opted to disable the `no-console` rule for this repo while in the process of cleaning up warnings since I just figured it was a testnet repo
> Add eslint to council-testnet app

- package.json
- yarn.lock
Issue: https://github.com/ardatan/whatwg-node/issues/54
> Pin cross-undici-fetch version to avoid bug in 0.4.14

- apps/core-v2-testnet/.eslintrc.js
- apps/core-v2-testnet/.prettierrc.js
- apps/core-v2-testnet/hardhat.config.ts
- apps/core-v2-testnet/package.json
- apps/core-v2-testnet/scripts/deploy.ts
- apps/core-v2-testnet/scripts/watch.ts
- apps/core-v2-testnet/tsconfig.json
- apps/core-v2-testnet/utils/logger.ts
- yarn.lock
- Started the logger functions which will standardize our output and make it more readable
- Created the watch scripts which saves evm_snapshot after every block and can revert N blocks. useful for testing frontend flows.
> Logger functions init and watch scripts

- apps/core-frontend/src/ui/wallets/IneligibleAccountDialog.tsx
> Update language for ineligible users

- apps/core-frontend/src/ui/app/Banner/TermsBanner.tsx
> Update banner in v1

- apps/core-frontend/src/ui/app/Banner/TermsBanner.tsx
> Update banner, include TOS language

- packages/component-library/README.md
Adding a readme.md file with installation instructions. While here I scaffolded out the other sections to be filled in later.
> Add readme for component library

- .github/workflows/update-core-v2-typechain.yml
- .github/workflows/update-delegates.yml
- packages/core-v2-typechain/scripts/load-contracts.sh
Ci job to build typechain types from newest changes in protocol-v2
also added a fix to install yarn in our update_delegates job
> [core-v2-typechain] CI for building typechain types daily

- packages/core-v2-sdk/src/example/index.ts
- packages/core-v2-sdk/src/models/Pool.ts
* added jsdocs to every function in the pool model
* added a tvl function
> [SDK] Pool TVL function and jsdocs for Pool model

- apps/core-frontend/src/elf/pools/calcPoolSwap.ts
- apps/core-frontend/src/elf/pools/calcSwapPrincipalPool.ts
- apps/core-frontend/src/ui/fixedrates/BuyFixedRatesView/BuyFixedRatesInputSelect.tsx
- packages/core-v2-sdk/src/datasources/MultiPool/MultiPoolContractDataSource.ts
- packages/core-v2-sdk/src/models/MultiPool.ts
Inputs of extremely small amounts (0.0000001) were crashing the app due to a rounding error.
> Fix rounding error causing v1 frontend to crash on small inputs

- apps/core-frontend/src/ui/pools/hooks/useExitConvergentCurvePool/useExitConvergentCurvePool.ts
Reverts element-fi/frontend-monorepo#400
This results in a negative value, and doesn't solve the gas estimation issue it originally seeks to fix:
> Revert "matt fix exitpool"

- apps/core-frontend/src/ui/pools/UnstakingPanel/UnstakingCard.tsx
- subtract fees for v1.1 ccpools during exit
> matt fix ui fees calc for withdraw

- apps/core-frontend/src/ui/fixedrates/FixedRatesListView.tsx
See: https://app.clickup.com/t/249ya58
> Fix sorting of fixed rates list

- apps/council-frontend/src/ui/app/PageView.tsx
- apps/council-frontend/src/ui/base/ExternalLink/ExternalLink.tsx
- apps/council-frontend/src/urls.ts
> Add banner deprecation notice

- apps/core-frontend/src/ui/app/AppHeader/AppHeader.tsx
- apps/core-frontend/src/ui/page/ExperimentalBanner/ExperimentalBanner.tsx
> Add sunset banner

- apps/nft-interface/src/constants.ts
Related to https://github.com/delvtech/hyperdrive-frontend/issues/1072
> Bump ToS local storage key
